# Generated by Django 5.2 on 2025-05-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musicians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullNames', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
    ]
